### ISSUE TITLE
[Bug] Allow VM to be created using disk image without specifying size_gb

### ISSUE THREAD

**Issue by yannickstruyf3** [nutanix/nutanix.ansible#127]
When creating a VM using a disk image, it is currently required to pass size_gb:

```
        disks:
          - type: "DISK"
            size_gb: 100
            clone_image:
              name: "{{image_name}}"
```
It should be possible to create a VM based on a disk_image without specifying the size_gb
