### ISSUE TITLE
[Feat] Allow environment variables for nutanix connection parameters

### ISSUE THREAD

**Issue by yannickstruyf3** [nutanix/nutanix.ansible#128]
Add the ability for users to set following parameters via environment variables:
- nutanix_host
- nutanix_username
- nutanix_password
- validate_certs
- nutanix_port

Similar to
```
        nutanix_hostname:
            description: Prism central hostname or IP address
            required: true
            type: str
            env:
                - name: NUTANIX_HOSTNAME
```
