### ISSUE TITLE
[Feat] Develop ansible module for inventory

### ISSUE THREAD

**Issue by peshay** [nutanix/nutanix.ansible#232]
Requirements:
- Enable [Constructed Features](https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html#constructed-features) for the inventory plugin
- It should also be possible to construct keyed groups based on the vm_name

Todo:
- [x] Examples

**Comment by peshay** [comment]
Example: I have a name schema to name VMs, based on this with my PR it is possible to put hosts directly in specific groups, based on the vm_name:

```yaml
plugin: nutanix.ncp.ntnx_prism_vm_inventory
keyed_groups:
  # group for customer name
  - prefix: ""
    separator: ''
    key: "vm_name | regex_replace('([a-zA-Z0-9]+)-([a-zA-Z0-9]+)-([a-zA-Z0-9]+)', '\\1')"
  # group for service name
  - prefix: ""
    separator: ''
    key: "vm_name | regex_replace('([a-zA-Z0-9]+)-([a-zA-Z0-9]+)-([a-zA-Z]+)[0-9]*', '\\3')"
  # group for environemnt name
  - prefix: ""
    separator: ''
    key: "vm_name | regex_replace('([a-zA-Z0-9]+)-([a-zA-Z0-9]+)-([a-zA-Z0-9]+)', '\\2')"
  # group for customer environemnt name
  - prefix: ""
    separator: ''
    key: "vm_name | regex_replace('([a-zA-Z0-9]+)-([a-zA-Z0-9]+)-([a-zA-Z0-9]+)', '\\1_\\2')"
```
