### ISSUE TITLE
[Bug] impossible to deploy NKE cluster with etcd using disk smaller than 120GB

### ISSUE THREAD

**Issue by Golgautier** [nutanix/nutanix.ansible#350]
**Describe the bug**
If you deploy a cluster and specify disk size smaller than 120 GB for etcd, it fails. With GUI, we can deploy ETCD with 40 GB disks.

**To Reproduce**
Deploy karbon cluster with these parameters for ETCD
```
        etcd:
          num_instances: 3
          cpu: 4
          memory_gb: 8
          disk_gb: 40
```

It should fail with this error :
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "error": "disk_gb cannot be less then 120",
    "invocation": {
        "module_args": {
            "cluster": {
                "uuid": "0005f824-09ff-ea11-671c-ac1f6b3b4ac8"
            },
            "cluster_type": "PROD",
            "cni": {
                "network_provider": "Flannel",
                "node_cidr_mask_size": 24,
```

**Expected behavior**
Allow 40 GB disk size on ETCD servers.
