### ISSUE TITLE
[Bug] Multiple filters params are not considered for fetching entities in PC based info modules

### ISSUE THREAD

**Issue by bhati-pradeep** [nutanix/nutanix.ansible#352]
**Describe the bug**
Currently, for example if a subnet is fetched based on name and cluster_name in filters, ntnx_subnets_info doesn't consider both filter. (i.e. "AND" behaviour)

**To Reproduce**
Run playbook task:
```yml
ntnx_subnets_info:
        filter:
          name: <vlan_name>
          cluster_name: <cluster name>
register: result
```
This playbook fetches all subnets from cluster name given.

**Expected behavior**
Info module should consider all filters for fetching entities.
