### ISSUE TITLE
[Bug] HTTP Error 422: UNPROCESSABLE ENTITY in module ntnx_subnets

### ISSUE THREAD

**Issue by nx-sbourdeaud** [nutanix/nutanix.ansible#376]
**Describe the bug**
When creating a VLAN subnet with an IPAM configuration in a PC with multiple PEs registered, the following error is shown:
`fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10"}, "changed": false, "error": "HTTP Error 422: UNPROCESSABLE ENTITY", "msg": "Failed fetching URL: https://10.68.97.150:9440/api/nutanix/v3/subnets", "response": null, "status_code": 422}`
**To Reproduce**
sample subnet section used:
```
- name: 'arthur_VLAN333'
      ntnx_subnets:
        state: present
        name: 'VLAN333'
        vlan_subnet:
          vlan_id: 333
          virtual_switch:
            uuid: '{{ virtual_switch_uuid }}'
          cluster:
            name: 'arthur'
          ipam:
            network_ip: '192.68.10.0'
            network_prefix: 24
            gateway_ip: '192.68.10.1'
            ip_pools:
              - start_ip: '192.68.10.20'
                end_ip: '192.68.10.25'
            dhcp:
              dns_servers: '{{ dns_servers }}'
              domain_search: '{{ domain_search }}'
              domain_name: '{{ domain_name }}'
              tftp_server_name: ''
              boot_file: ''
              dhcp_server_ip: ''
      register: result
      ignore_errors: true
```

**Stack trace**

**Expected behavior**
VLAN subnet with IPAM section gets created successfully.

**Additional context**
