### ISSUE TITLE
[Bug] storage container without size specified is considered valid by VM Spec + API, failed vm creation in ntnx_vms

### ISSUE THREAD

**Issue by omarqureshi** [nutanix/nutanix.ansible#385]
**Describe the bug**
If you create a VM with a storage container attached as disk and fail to provide a size for it, it initially succeeds (HTTP 202) but eventually fails (HTTP 500 from task list). The HTTP 500 is very vague and took me some time to figure out where it was happening by modifying entity._fetch_url to get at what was being sent to Prism Central's API

**To Reproduce**
```yaml
    - ntnx_vms:
        state: present
        name: "{{ vm_name }}"
        timezone: UTC
        cluster:
          name: "{{ nutanix.cluster_name }}"
        vcpus: "{{ vcpus }}"
        cores_per_vcpu: "{{ cores_per_vcpu }}"
        memory_gb: "{{ memory_gb }}"
        networks:
          - is_connected: true
            subnet:
              name: "{{ nutanix.static_subnet_name }}"
        disks:
          - type: DISK
            bus: SCSI
            size_gb: "{{ ephemeral_disk_size_gb }}"
          - type: DISK
            bus: SCSI
            storage_container:
              name: "{{ storage_container_name }}"
          - type: CDROM
            bus: SATA
            clone_image:
              name: "{{ image_name }}"
        boot_config:
          boot_type: LEGACY
          boot_order:
            - CDROM
            - DISK
            - NETWORK
```

**Stack trace**
HTTP 500 without any context as to why it was failing

**Expected behavior**
The failure is right, however, this should have been caught when checking the yaml spec and not when attempting to create the VM. Probably need to change DefaultVMSpec to do this

**Additional context**
This probably extends to other disk attributes too, looking at DefaultVMSpec, this does not validate the shape of the disks list
