### ISSUE TITLE
Fragile Code: Specifying Cluster on Non-Multiple Subnet Name Results in Subnet Not Found

### ISSUE THREAD

**Issue by jhowe-uw** [nutanix/nutanix.ansible#387]
https://github.com/nutanix/nutanix.ansible/blob/923e9c76915c55006882df6b0623ffb781ed854d/examples/vm.yml#L35

The code block below states you need to specify the cluster name when the subnet name exists across multiple clusters. However, this puts the onus of detecting multiple subnet names on the user and creates non-DRY ansible playbooks.

Expected:

Stating a cluster name for a subnet should always be successful, regardless if the subnet is a single instance or has multiple instances across clusters.

Actual:

Stating a cluster name on a subnet with no duplicates results in subnet not found

Additional:

Note the misspelling on line 35 of accross ( -> across )

Thanks!

```
networks:
        - is_connected: True
          subnet:
            name: "{{ subnet_name }}"
            # mention cluster only when there are multiple subnets with same name accross clusters
            # and subnet name is set above
            cluster:
              name: "{{cluster_name}}"
```
