### ISSUE TITLE
[Imprv] add functionality to provide sysprep or cloud-init to module ntnx_vms via a variable instead of a file

### ISSUE THREAD

**Issue by grdavies** [nutanix/nutanix.ansible#389]
**Describe the request**
Currently the only way to provide customization scripts is via a parameter that takes the file path of the customization script that is to be applied. This approach requires the script to either pre-exist or be generated (via a jinja template for example) and stored as a file before being used by the script. This can cause potentially a buildup of unnecessary scripts on the system that the playbook is being run from. As these scripts ofter contain sensitive information like local administrative passwords etc. this can also pose a security risk.

I would like to provide the customization script to the ntnx_vms module parameter directly from the template instead of first having to save the template as a file.

**Current behaviour**
ntnx_vms:
  state: present
  ...
  guest_customization:
    type: "cloud_init"
    script_path: "./cloud_init.yml"
    is_overridable: True

**Expected behaviour**
ntnx_vms:
  state: present
  ...
  guest_customization:
    type: "cloud_init"
    script: "{{ lookup('template', 'sysprep.j2') }}"
    is_overridable: True

**Comment by elwood218** [comment]
+1 That would be awesome! Instead of giving a path to a file it would be better to read userdata from a Ansible template.

**Comment by bhati-pradeep** [comment]
Review in progress. Moved to 1.9.2

**Comment by bhati-pradeep** [comment]
Hi @grdavies, In v4 we have ntnx_vms_v2 module which supports this. Can you check if this helps your usecase ?

**Comment by cptBlackBeer** [comment]
Hi @bhati-pradeep 
I was trying to create a VM with cloud-init config using the ntnx_vms_v2 module but I can't get it to work. So if found this issue here. 

This is my cloud-init Script (removed keys and passwords):
```yml
#cloud-config
hostname: TestVM
users:
  - name: some_user
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    lock_passwd: true
    groups: sudo
    ssh_authorized_keys:
      - ssh-ed25519 ...
  - name: root
    hashed_passwd: ...
write_files:
  - path: /etc/netplan/99-custom-network.yaml
    content: |
      network:
        version: 2
        ethernets:
          ens3:
            addresses:
              - 192.168.99.177/24
            routes:
              - to: 192.168.99.0/24
                via: 192.168.99.1
            nameservers:
              addresses:
                - 192.168.99.1
runcmd:
  - curl -sL 'https://apt.netmaker.org/gpg.key' | gpg --dearmor -o /usr/share/keyrings/netmaker-keyring.gpg
  - echo \"deb [signed-by=/usr/share/keyrings/netmaker-keyring.gpg] https://apt.netmaker.org stable main\" > /etc/apt/sources.list.d/netclient.list
  - apt update
  - apt install -y netclient
package_update: true
package_upgrade: true
packages: ['bash-completion', 'cloud-utils', 'curl', 'gpg', 'gpg-agent', 'htop', 'inetutils-traceroute', 'ncdu', 'rsync', 'sudo', 'vim']

```

Ansible taks:
```yml
- name: Deploy server on Nutanix v2
  nutanix.ncp.ntnx_vms_v2:
    state: present
    name: "{{ server_hostname }}"
    nutanix_host: "{{ nutanix_host }}"
    nutanix_username: "{{ nutanix_user }}"
    nutanix_password: "{{ nutanix_pw }}"
    validate_certs: false
    hardware_clock_timezone: "{{ timezone }}"
    cluster:
      ext_id: "{{ nutanix_cluster_ext_id }}"
    nics: "{{ networks }}"
    disks: "{{ disks }}"
    boot_config:
      uefi_boot:
        is_secure_boot_enabled: '{{ true if "windows" in nb_virtual_machine[0].value.platform.slug else false }}'
    num_sockets: 1
    num_cores_per_socket: "{{ nb_virtual_machine[0].value.vcpus | int }}"
    memory_size_bytes: '{{ nb_virtual_machine[0].value.memory | human_to_bytes(default_unit="M") }}'
    vtpm_config:
      is_vtpm_enabled: true
    guest_customization:
      config:
        cloudinit:
          cloud_init_script:
            user_data:
              value: "{{ cloud_init_config }}"
```

No matter what I try, I always get this Error from Nutanix:
`"code": "VMM-30102", "error_group": "VM_INVALID_ARGUMENT", "locale": "en_US", "message": "Failed to perform the operation on the VM with UUID '{{{vm_uuid}}}', due to an invalid argument with key 'userdata' and value`

When creating a VM manually in Prism Central with the exact same cloud-init script it works fine. 
Am I missing something?

**Comment by bhati-pradeep** [comment]
> cloud_init_config

```
guest_customization:
      config:
        cloudinit:
          datasource_type: CONFIG_DRIVE_V2
          cloud_init_script:
            user_data:
              value: "{{ cloud_init_config }}"
```

Can you please try this with adding `datasource_type` and check. Also can you share whats the check_mode response ?

**Comment by cptBlackBeer** [comment]
Hi @bhati-pradeep 
Thanks for your reply. I tried it with `datasource_type: CONFIG_DRIVE_V2` but unfortunately with the same result. Same error message.
This ist the output of check_mode:

```
ok: [localhost] => {"changed": false, "error": null, "ext_id": null, "response": {"apc_config": null, "availability_zone": null, "bios_uuid": null, "boot_config": {"boot_device": null, "boot_order": null, "is_secure_boot_enabled": false, "nvram_device": null}, "categories": null, "cd_roms": null, "cluster": {"ext_id": "00062f21-936c-3c60-5488-7cc2558b82fb"}, "create_time": null, "description": null, "disks": [{"backing_info": {"data_source": {"reference": {"image_ext_id": "46cf8cbe-ba38-4221-9ca1-a3d95fdddcf6"}}, "disk_ext_id": null, "disk_size_bytes": null, "is_migration_in_progress": null, "storage_config": null, "storage_container": null}, "disk_address": {"bus_type": "SCSI", "index": null}, "ext_id": null, "links": null, "tenant_id": null}, {"backing_info": {"data_source": null, "disk_ext_id": null, "disk_size_bytes": 10737418240, "is_migration_in_progress": null, "storage_config": null, "storage_container": {"ext_id": "a125ec07-d769-486d-83f6-e1c01fcff515"}}, "disk_address": {"bus_type": "SCSI", "index": null}, "ext_id": null, "links": null, "tenant_id": null}], "enabled_cpu_features": null, "ext_id": null, "generation_uuid": null, "gpus": null, "guest_customization": {"config": {"cloud_init_script": {"value": "#cloud-config hostname: TestVM-KPE users:\n  - name: svc_automation\n    shell: /bin/bash\n    sudo: ['ALL=(ALL) NOPASSWD:ALL']\n    lock_passwd: true\n    groups: sudo\n    ssh_authorized_keys:\n      - ssh-ed25519 ...\n  - name: root\n    hashed_passwd: password\nwrite_files:\n  - path: /etc/netplan/99-custom-network.yaml\n    content: |\n      network:\n        version: 2\n        ethernets:\n             ens3:\n          # test\n            addresses:\n              - 192.168.99.177/24\n            routes:\n              - to: 192.168.99.0/24\n
    via: 192.168.99.1\n            nameservers:\n              addresses:\n                - 192.168.99.1\n \nruncmd:\n  - curl -sL 'https://apt.netmaker.org/gpg.key' | gpg --dearmor -o /usr/share/keyrings/netmaker-keyring.gpg\n  - echo \"deb [signed-by=/usr/share/keyrings/netmaker-keyring.gpg] https://apt.netmaker.org stable main\" > /etc/apt/sources.list.d/netclient.list\n  - apt update\n  - apt install -y netclient\npackage_update: true package_upgrade: true packages: ['bash-completion', 'cloud-utils', 'curl', 'gpg', 'gpg-agent', 'htop', 'inetutils-traceroute', 'ncdu', 'rsync', 'sudo', 'vim']"}, "datasource_type": "CONFIG_DRIVE_V2", "metadata": null}}, "guest_tools": null, "hardware_clock_timezone": "Europe/Zurich", "host": null, "is_agent_vm": null, "is_branding_enabled": null, "is_cpu_hotplug_enabled": null, "is_cpu_passthrough_enabled": null, "is_cross_cluster_migration_in_progress": null, "is_gpu_console_enabled": null, "is_live_migrate_capable": null, "is_memory_overcommit_enabled": null, "is_scsi_controller_enabled": null, "is_vcpu_hard_pinning_enabled": null, "is_vga_console_enabled": null, "links": null, "machine_type": null, "memory_size_bytes": 4294967296, "name": "TestVM-KPE", "nics": [{"backing_info": {"is_connected": true, "mac_address": null, "model": null, "num_queues": 1}, "ext_id": null, "links": null, "network_info": {"ipv4_config": null, "ipv4_info": null, "network_function_chain": null, "network_function_nic_type": null, "nic_type": null, "should_allow_unknown_macs": null, "subnet": {"ext_id": "8b0ecc5e-1f29-4e9b-8ddf-41ba7ea9f36b"}, "trunked_vlans": null, "vlan_mode": null}, "tenant_id": null}], "num_cores_per_socket": 2, "num_numa_nodes": null, "num_sockets": 1, "num_threads_per_core": null, "ownership_info": null, "pcie_devices": null, "power_state": null, "protection_policy_state": null, "protection_type": null, "serial_ports": null, "source": null, "storage_config": null, "tenant_id": null, "update_time": null, "vtpm_config": {"is_vtpm_enabled": true, "version": null}}, "task_ext_id": null}
```

**Comment by cptBlackBeer** [comment]
Hi @bhati-pradeep 
With base64 encoded and `datasource_type: CONFIG_DRIVE_V2` it works now 🥳 
Maybe also mention in the docs that  `datasource_type: CONFIG_DRIVE_V2` is also required when using `user_data`

My working task:

````
- name: Deploy server on Nutanix v2
  nutanix.ncp.ntnx_vms_v2:
    state: present
    name: "{{ server_hostname }}"
    nutanix_host: "{{ nutanix_host }}"
    nutanix_username: "{{ nutanix_user }}"
    nutanix_password: "{{ nutanix_pw }}"
    validate_certs: false
    hardware_clock_timezone: "{{ timezone }}"
    cluster:
      ext_id: "{{ nutanix_cluster_ext_id }}"
    nics: "{{ networks }}"
    disks: "{{ disks }}"
    boot_config:
      uefi_boot:
        is_secure_boot_enabled: '{{ true if "windows" in nb_virtual_machine[0].value.platform.slug else false }}'
    num_sockets: 1
    num_cores_per_socket: "{{ nb_virtual_machine[0].value.vcpus | int }}"
    memory_size_bytes: '{{ nb_virtual_machine[0].value.memory | human_to_bytes(default_unit="M") }}'
    vtpm_config:
      is_vtpm_enabled: true
    guest_customization:
      config:
        cloudinit:
          datasource_type: CONFIG_DRIVE_V2
          cloud_init_script:
            user_data:
              value: "{{ cloud_init_config | b64encode }}"
```

Thanks for your help

**Comment by cptBlackBeer** [comment]
@bhati-pradeep I tried the same now with Windows and run into the same problem. 
I've created a unattend.xml which works fine when creating VMs in PC Web Interface. 
But using the same XML  with the Ansible module results in the error:
`"error_messages": [{"arguments_map": {"argument_key": "unattendXml", "argument_value":"my XML content"`
I tried it also with b64encode but then i get the error:
`"error_messages": [{"arguments_map": null, "code": "VMM-30102", "error_group": "VM_INVALID_ARGUMENT"`

This is the Ansible Task:
```yml
- name: Deploy server on Nutanix
  nutanix.ncp.ntnx_vms_v2:
    state: present
    name: "{{ server_hostname }}"
    hardware_clock_timezone: UTC #set correct timezone in VM
    cluster:
      ext_id: "{{ nutanix_cluster_ext_id }}"
    nics: "{{ networks }}"
    disks: "{{ disks }}"
    boot_config:
      uefi_boot:
        is_secure_boot_enabled: true
    num_sockets: 1
    num_cores_per_socket: "{{ nb_virtual_machine[0].value.vcpus | int }}"
    memory_size_bytes: '{{ nb_virtual_machine[0].value.memory | human_to_bytes(default_unit="M") }}'
    vtpm_config:
      is_vtpm_enabled: true
    guest_customization:
      config:
        sysprep: 
          install_type: 'PREPARED'
          sysprep_script:
            unattendxml:
              value: "{{ autounattendxml }}"
  register: ntnx_vm_result
```

Example unattend.xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:schemas-microsoft-com:unattend">
    <settings pass="specialize">
        <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
            <InputLocale>de-CH</InputLocale>
            <SystemLocale>de-CH</SystemLocale>
            <UILanguage>en-US</UILanguage>
            <UserLocale>de-CH</UserLocale>
        </component>
        <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
            <ComputerName>Testserver</ComputerName>
        </component>
        <component name="Microsoft-Windows-TerminalServices-LocalSessionManager" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
            <fDenyTSConnections>false</fDenyTSConnections>
        </component>
        <component name="Networking-MPSSVC-Svc" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
            <FirewallGroups>
                <FirewallGroup wcm:action="add" wcm:keyValue="rd1">
                    <Active>true</Active>
                    <Group>Remote Desktop</Group>
                    <Profile>all</Profile>
                </FirewallGroup>
            </FirewallGroups>
        </component>
        <component name="Microsoft-Windows-ServerManager-SvrMgrNc" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
            <DoNotOpenServerManagerAtLogon>true</DoNotOpenServerManagerAtLogon>
        </component>
    </settings>
    <settings pass="oobeSystem">
        <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
            <InputLocale>de-CH</InputLocale>
            <SystemLocale>de-CH</SystemLocale>
            <UILanguage>en-US</UILanguage>
            <UserLocale>de-CH</UserLocale>
        </component>
        <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
            <UserAccounts>
                <AdministratorPassword>
                    <Value>SomePassword</Value>
                    <PlainText>true</PlainText>
                </AdministratorPassword>
            </UserAccounts>
            <OOBE>
                <ProtectYourPC>1</ProtectYourPC>
                <HideEULAPage>true</HideEULAPage>
                <HideLocalAccountScreen>true</HideLocalAccountScreen>
                <HideOEMRegistrationScreen>true</HideOEMRegistrationScreen>
                <HideOnlineAccountScreens>true</HideOnlineAccountScreens>
                <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>
            </OOBE>
            <TimeZone>W. Europe Standard Time</TimeZone>
        </component>
    </settings>
</unattend>
```

Looking at the examples and the documentation i couldn't figure out how to properly provide the xml. Is this a bug or a mistake on my side?
