### ISSUE TITLE
[Bug] ntnx_ndb_time_machines_info not fetching all attributes when name is used for fetching

### ISSUE THREAD

**Issue by bhati-pradeep** [nutanix/nutanix.ansible#418]
**Describe the bug**
ntnx_ndb_time_machines_info not fetching all attributes when name is used for fetching. It only gives basic info. When UUID is used it gives all attributes like metadata, sla info, snapshot schedules, etc.

**To Reproduce**
```yml
- name: get ndb time machines using it's name
  ntnx_ndb_time_machines_info:
    name: "TM1"
    filters:
      detailed: true
```

**Expected behavior**
It should give all attributes.
