### ISSUE TITLE
[Bug] Ansible reports success when power-off fails in module nutanix.ncp.ntnx_vms

### ISSUE THREAD

**Issue by thewelshvader** [nutanix/nutanix.ansible#439]
Using the nutanix.ncp.ntnx_vms module to power-off a VM, the ansible output reports a success, even when an error occurs.
VMs are not always powered down correctly, but ansible always produces the same successful output.

<img width="579" alt="Screenshot 2023-11-20 at 11 05 58" src="https://github.com/nutanix/nutanix.ansible/assets/54893059/f71fa4b9-b3b9-452d-8dfd-767781bc81df">

The underlying error can be seen in the Prism Central UI and the verbose ansible log as per below.

{
  "changed": true,
  "error": null,
  "response": {
    "status": {
      "name": "m*********8",
      "state": "ERROR",
      "execution_context": {
        "task_uuid": [
          "37d3e6d*******-******-0489"
        ]
      },

**To Reproduce**
Sample from ansible role:
```
---
# tasks file for prism-vm-soft-shutdown
- name: "Shutdown Guest OS"
  nutanix.ncp.ntnx_vms:
    nutanix_host: "{{ nutanix_url }}"
    nutanix_username: '{{ nutanix_username }}'
    nutanix_password: '{{ nutanix_password }}'
    vm_uuid: "{{ vm_uuid }}"
    state: soft_shutdown
  register: shutdown_result
  delegate_to: localhost
```

**Expected behavior**
When an error is returned by the Prism Central UI, ansible should fail the task instead of reporting successful.

**Additional context**
Nutanix support confirmed that an AOS update may be needed to resolve the power-off issue.
The issue here is that our ansible playbooks are always marking the task as _Successful_, even when we can clearly see an error in the API response and in the Prism Central UI.
