### ISSUE TITLE
[Bug] ntnx_clusters_info and ntnx_hosts_info filters does not filter

### ISSUE THREAD

**Issue by mdhowle** [nutanix/nutanix.ansible#472]
**Describe the bug**
When using ntnx_clusters_info and applying a filter of `name: CLUSTERNAME`, all clusters are returned when only _CLUSTERNAME_ should be returned

Similarly, when using ntnx_hosts_info and applying a filter of `cluster_name: CLUSTERNAME`, all hosts are returned when only hosts in the _CLUSTERNAME_ cluster should be returned.

However, ntnx_vms_info with a filter `cluster_name: CLUSTERNAME`, returns only those VMs hosted within the _CLUSTERNAME_ cluster.

**To Reproduce**
`ansible-playbook -i localhost, -c local playbook.yml`

```yaml
---
- name: Test playbook
  hosts: all
  tasks:
    - name: Get cluster info
      nutanix.ncp.ntnx_clusters_info:
        nutanix_host: "{{ prism_host }}"
        nutanix_username: "{{ prism_username }}"
        nutanix_password: "{{ prism_password }}"
        filter:
          name: "{{ cluster_name }}"
      register: cluster_info

    - name: Assert cluster info is only one result
       assert:
          that: cluster_info.response.entitites | length == 1

    - name: Get hosts info
      nutanix.ncp.ntnx_clusters_info:
        nutanix_host: "{{ prism_host }}"
        nutanix_username: "{{ prism_username }}"
        nutanix_password: "{{ prism_password }}"
        filter:
          cluster_name: "{{ cluster_name }}"
      register: hosts_info

    - name: Assert hosts info has five or fewer hosts
       assert:
          that: hosts_info.response.entitites | length <= 5  
```

**Expected behavior**
For ntnx_clusters_info, it should only return the one cluster that matched the cluster name given in the filter.

For ntnx_hosts_info, it should return a list of hosts that matched the cluster name given in the filter.

**Additional context**
This may be similar to #374 with a different module and using custom_filter.

This occurs in both nutanix.ncp versions 1.9.0 and 1.9.1
