### ISSUE TITLE
[Bug] fail to get dynamic inventory for more > 50/90 VMs in module ntnx_prism_vms_inventory

### ISSUE THREAD

**Issue by nahsiy** [nutanix/nutanix.ansible#483]
Following the migration of our central prism **from pc.2022.6.7 to 2024.1**, our ntnx_prism_vms_inventory plugin no longer works without an explicit error, as soon as we set a lenght of more than 50/90.

**Via curl or postman, it works for 500 VMs, which seems to be the limit.** 

our inventory code :

---
```
plugin: nutanix.ncp.ntnx_prism_vm_inventory
strict: false
nutanix_hostname: "{{cluster}}""
nutanix_port: "" # Make sure the port is correct
validate_certs: false
data: {"offset": 0, "length": 1000}
groups:
  vm_OFF: "'OFF' in power_state"
  vm_NGT: "'INSTALLED' in guest_tools.nutanix_guest_tools.ngt_state"
keyed_groups:
  - prefix: "vm_ZONE"
    separator: ':'
    key: "ntnx_categories.ZONE"
  - prefix: "vm_SITE"
    separator: ':'
    key: "ntnx_categories.SITE"
  - prefix: "vm_OS"
    separator: ':'
    key: "ntnx_categories.OS"
  - prefix: "vm_MCO"
    separator: ':'
    key: "ntnx_categories.MCO"
```

before this migration, we had no problem recovering all the VMs in our cluster (554VMS) with this configuration
