### ISSUE TITLE
[Bug] "Failed to convert API response into JSON" in all modules of Nutanix.ncp ansible collection

### ISSUE THREAD

**Issue by marathe-99** [nutanix/nutanix.ansible#490]
**Describe the bug**
In this Nutanix Ansible Collection when we ran any of the modules it threw the same error "Failed to convert API response into JSON"

**To Reproduce**
1. ansible command
2. sample playbook used.

![image](https://github.com/user-attachments/assets/9d2511bd-dea1-4437-8b18-e1ff16f7d2df)

**Expected behavior**
It should give the information of the imaged nodes.

**Additional context**
![image](https://github.com/user-attachments/assets/0f953748-2ebf-411b-b416-3b51b315b718)

**Comment by marathe-99** [comment]
Please rectify the issue and resolve the issue it's very important.

**Comment by konstruktoid** [comment]
Related PR: https://github.com/nutanix/nutanix.ansible/pull/486

**Comment by bhati-pradeep** [comment]
@marathe-99 meanwhile this issue is resolved (which will need a maintenance release), can you tell me which way are you using this plugin ? So that I can suggest you a way to look into this error. 

Also this error can come if your response was empty. 
1. Verify your spec is as per documented module spec
2. (Optional) Check the foundation UI if the task has been created or not.

**Comment by koladiya** [comment]
Hi @bhati-pradeep, thanks for the quick reply.
trying to test the below simple playbook on RedHat ansible automation platform. & later automate further tasks.
```
---
- name: Clusters_Info playbook
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: "{{ nutanix_host }}"
      nutanix_username: "{{ nutanix_username }}"
      nutanix_password: "{{ nutanix_password }}"
      validate_certs: "{{ validate_certs }}"
 
  tasks:
    - name: Test getting all clusters
      nutanix.ncp.ntnx_clusters_info:
      register: clusters
 
    - name: Test getting particular cluster using uuid
      nutanix.ncp.ntnx_clusters_info:
        cluster_uuid: "{{ clusters.response.entities[0].metadata.uuid }}"
      register: result 
.
.
.

```
