### ISSUE TITLE
nutanix.ncp.ntnx_vms when clone disk from image device file sys_wwid pvid last seen on /dev/sd# not found

### ISSUE THREAD

**Issue by darthVikes** [nutanix/nutanix.ansible#507]
**Describe the bug**

When using the nutanix.ncp.ntnx_vms function and clone_image from the disk image getting : 

"Device file sys_wwid t10.NUTANIX.NFS_3_0_UUID Last seen on /dev/sdb not found"

During Linux boot, this is RHEL 9.x

**To Reproduce**

ansible-playbook playbook.yaml

```
    - name: Create VM
      nutanix.ncp.ntnx_vms:
        state: present
        name: "ansible_automation_demo"
        desc: "ansible_vm_description"
        cluster:
          name: "{{ ntnx_cluster }}"
        networks:
          - is_connected: true
            subnet:
              name: "{{ subnet_name }}"
              cluster:
                name: "{{ ntnx_cluster }}"
        disks:
          - type: "DISK"
            size_gb: 1
            bus: "SCSI"
            clone_image:
              name: "{{ image_name }}"
          - type: "DISK"
            size_gb: 50
            bus: "SCSI"
            clone_image:
              name: "{{ image_name }}-disk2"
          - type: "DISK"
            size_gb: 5
            bus: "SCSI"
            clone_image:
              name: "{{ image_name }}-disk3"
```

/boot =  sda
/        =  sdb
/data = sdc 

**Stack trace**

![image](https://github.com/user-attachments/assets/7e65c98b-7478-4648-93a1-5e4af53b63a6)

**Expected behavior**
It would find the disk, and boot.
