### ISSUE TITLE
[Bug] no attributes 'TasksApi' and 'get_task_by_id'  when using module ntnx_images_v2

### ISSUE THREAD

**Issue by konstruktoid** [nutanix/nutanix.ansible#576]
**Describe the bug**
Trying to upload an image using `ntnx_images_v2` results in two (initial) errors, and fails to upload any image.

**To Reproduce**
Trying to upload an image using `ntnx_images_v2` results in two (initial) errors.
Fist it reports that `'ntnx_prism_py_client' has no attribute 'TasksApi'`, and
after patching that, it reports `AttributeError: 'TaskApi' object has no attribute 'get_task_by_id'`.

```yaml
    - name: Setting Variables
      ansible.builtin.set_fact:
        image_name: oracular-server-cloudimg-amd64
        source_url: https://cloud-images.ubuntu.com/oracular/current/oracular-server-cloudimg-amd64.img
        checksum_algorithm: SHA_256
        checksum_value: 47588c0e96c16c891b3e0372c4650acec96415bf3fdd0f0705d23e519e18e4a3
        image_type: DISK_IMAGE
        product_name: Ubuntu Linux
        product_version: "24.10"
        desc: "Ubuntu 24.10 (Oracular Oriole)"

    - name: Upload image
      nutanix.ncp.ntnx_images_v2:
        nutanix_host: "{{ ntnx_cluster.prism_central }}"
        nutanix_username: "{{ vault_admin_username }}"
        nutanix_password: "{{ vault_admin_password }}"
        name: "{{ image_name }}"
        type: "{{image_type}}"
        source:
          url_source:
            url: "{{ source_url }}"
        checksum:
          sha256:
            hex_digest: "{{ checksum_value }}"
        description: "{{ desc }}"
        state: present
        wait: true
```

```
/nutanix/ncp/plugins/module_utils/v4/prism/tasks.py\", line 48, in wait_for_completion\nAttributeError: module 'ntnx_prism_py_client' has no attribute 'TasksApi'. Did you mean: 'TaskApi'?\n", "module_stdout": ""
, "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

```diff
$ git diff
diff --git a/plugins/module_utils/v4/prism/tasks.py b/plugins/module_utils/v4/prism/tasks.py
index ba75d3c7..960c1617 100644
--- a/plugins/module_utils/v4/prism/tasks.py
+++ b/plugins/module_utils/v4/prism/tasks.py
@@ -45,7 +45,7 @@ def wait_for_completion(
         Task data.
     """
     api_client = get_pc_api_client(module=module)
-    tasks = ntnx_prism_py_client.TasksApi(api_client=api_client)
+    tasks = ntnx_prism_py_client.TaskApi(api_client=api_client)

     # add encoded service prefix to create complete task external ID
     if add_task_service:
```

```
/nutanix/ncp/plugins/module_utils/v4/prism/tasks.py\", line 66, in wait_for_completion\nAttributeError: 'TaskApi' object has no attribute 'get_task_by_id'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee std
out/stderr for the exact error", "rc": 1}
```

**Expected behavior**

Upload image.

**Additional context**

Python3:

```sh
ansible                       10.7.0
ansible-compat                24.10.0
ansible-core                  2.17.7
ntnx-clustermgmt-py-client    4.0.1
ntnx-dataprotection-py-client 4.0.1
ntnx-iam-py-client            4.0.1
ntnx-lifecycle-py-client      4.0.1
ntnx-microseg-py-client       4.0.1
ntnx-networking-py-client     4.0.1
ntnx-prism-py-client          4.0.3a2
ntnx-vmm-py-client            4.0.1
ntnx-volumes-py-client        4.0.1
```

Ansible
```
ansible [core 2.17.7]
nutanix.ncp 2.0.0 (built locally from main with above patch)
```
