### ISSUE TITLE
[Bug] Cannot assign IP address on an unmanaged network in module ntnx_vms

### ISSUE THREAD

**Issue by motorbass0** [nutanix/nutanix.ansible#593]
**Describe the bug**
Unable to update VM's subnets since PC has been upgraded from 2022.X to pc.2024.2.0.3

**To Reproduce**
```
---
- name: test-playbook
  hosts: localhost

  vars:
    nutanix_host: "{{ nutanix_pc }}"
    nutanix_username: "{{ nutanix_account }}"
    nutanix_password: "{{ nutanix_password }}"
    new_vlan: "VLAN-XXXXX"
    cluster_name: "PE-CLUSTER"
    hostname: "VM-HOSTNAME"

### COLLECTIONS ###
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: "{{ nutanix_pc }}"
      nutanix_username: "{{ nutanix_account }}"
      nutanix_password: "{{ nutanix_password }}"


### TASKS ###
  tasks:
  - name: Recuperation des infos de la VM depuis Prism Central
    ntnx_vms_info:
      nutanix_host: "{{ nutanix_pc }}"
      nutanix_username: "{{ nutanix_account }}"
      nutanix_password: "{{ nutanix_password }}"
      validate_certs: False
      filter:
        vm_name: "{{ hostname }}"
      kind: vm
    register: result

  - name: Update VM subnet on PC
    ntnx_vms:
      nutanix_host: "{{ nutanix_pc }}"
      nutanix_username: "{{ nutanix_account }}"
      nutanix_password: "{{ nutanix_password }}"
      validate_certs: False

      vm_uuid: "{{ result.response.entities[0].metadata.uuid }}"
      networks:
        - is_connected: true
          subnet:
            name: "{{ new_vlan }}"
          uuid: "{{ result.response.entities[0].spec.resources.nic_list[0].uuid }}"
        - is_connected: true
          subnet:
            name: "{{ new_vlan }}"
          uuid: "{{ result.response.entities[0].spec.resources.nic_list[1].uuid }}"
```

**Stack trace**
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "error": "INVALID_ARGUMENT: Cannot assign IP address on an unmanaged network: 10",
    "invocation": {
        "module_args": {
            "force_power_off": false,
            "networks": [
                {
                    "is_connected": true,
                    "private_ip": "10.10.10.10",
                    "subnet": {
                        "name": "VLAN-XXXX"
                    },
                    "uuid": "1876e52f-a638-406f-84ae-8bc971b1d519"
                },
                {
                    "is_connected": true,
                    "private_ip": "10.10.10.11",
                    "subnet": {
                        "name": "VLAN-XXXX"
                    },
                    "uuid": "fe577643-78a0-469d-a845-17c45a94d7ee"
                }
            ],
            "nutanix_host": "my_prism.com",
            "nutanix_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "nutanix_port": "9440",
            "nutanix_username": "my_username",
            "remove_categories": false,
            "state": "present",
            "timezone": "UTC",
            "validate_certs": false,
            "vm_uuid": "c9600782-808b-4889-90fe-6953acdffa6e",
            "wait": true
        }
    },
    "msg": "INVALID_ARGUMENT: Cannot assign IP address on an unmanaged network: 10",
    "response": {
        "api_version": "3.1",
        "cluster_reference": {
            "kind": "cluster",
            "uuid": "80c970d8-06b1-4ac8-b527-72719b8549f4"
        },
        "completion_time": "2025-02-19T16:24:20Z",
        "completion_time_usecs": 1739982260620073,
        "creation_time": "2025-02-19T16:24:17Z",
        "creation_time_usecs": 1739982257325182,
        "entity_reference_list": [
            {
                "kind": "vm",
                "uuid": "c9600782-808b-4889-90fe-6953acdffa6e"
            }
        ],
        "error_code": "400",
        "error_detail": "INVALID_ARGUMENT: Cannot assign IP address on an unmanaged network: 10",
        "last_update_time": "2025-02-19T16:24:20Z",
        "logical_timestamp": 2,
        "operation_type": "update_vm_intentful",
        "percentage_complete": 100,
        "progress_message": "update_vm",
        "start_time": "2025-02-19T16:24:17Z",
        "start_time_usecs": 1739982257507506,
        "status": "FAILED",
        "subtask_reference_list": [],
        "uuid": "6a4d6708-7203-4550-96f0-bea2eb5a166b"
    },
    "status_code": "400"
}
```

**Expected behavior**
Module used to successfully update VM subnet. At the moment, it raises "Cannot assign IP address on an unmanaged network: 10" fatal error.

**Additional context**
Current VM is on a managed network that provide DHCP (for basic provisioning), when it goes to customization, we have to update subnet to an unmanaged one (because we manage IP address from the VM's OS perspective)
