### ISSUE TITLE
[Bug] Error "AnsibleModule.fail_json() takes 2 positional arguments but 3 were given" in module ntnx_vms_ngt_upgrade_v2

### ISSUE THREAD

**Issue by khismatullinmax** [nutanix/nutanix.ansible#601]
**Describe the bug**
We never used before this collection and found it for NGT the automatic upgrading. We want to upgrade NGT only using this collection. 

*Nutanix PC version*: pc.2024.3.0.1
*AOS*: 7.0.0.5
*AHV*: 10.0.0.1

**To Reproduce**
1. ansible command
```
ansible-playbook playbooks/upgrade-ngt.yml -vv 
```

2. sample playbook used
```
- name: Upgrade NGT
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: "_nutanix_pc_url"
      nutanix_username: "_nutanix_pc_user"
      nutanix_password: "_nutanix_pc_password"
      validate_certs: false
  vars:
    vm_uuid: "_vm_uiid"
  tasks:

  - name: Upgrade NGT in VM
    nutanix.ncp.ntnx_vms_ngt_upgrade_v2:
      state: present
      ext_id: "{{ vm_uuid }}"
      reboot_preference:
        schedule_type: "SKIP"
    register: result
```

**Stack trace**
```
ansible-playbook [core 2.16.3]
  config file = /home/user/ansible-playbook/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
Using /home/user/ansible-playbook/ansible.cfg as config file
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: upgrade-ngt.yml *****************************************************************************************************************************************************************************************************
1 plays in playbooks/upgrade-ngt.yml

PLAY [Upgrade NGT] ************************************************************************************************************************************************************************************************************

TASK [Upgrade NGT in VM] ******************************************************************************************************************************************************************************************************
task path: /home/user/ansible-playbook/playbooks/upgrade-ngt.yml:33
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: AnsibleModule.fail_json() takes 2 positional arguments but 3 were given
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/user/.ansible/tmp/ansible-tmp-1741015132.8895566-147971-69429608548515/AnsiballZ_ntnx_vms_ngt_upgrad
e_v2.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/user/.ansible/tmp/ansible-tmp-1741015132.8895566-147971-69429608548515/AnsiballZ_ntnx_vms_ngt_upgrade_v2.py\", line 99, in _ansiballz_main\n    inv
oke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/user/.ansible/tmp/ansible-tmp-1741015132.8895566-147971-69429608548515/AnsiballZ_ntnx_vms_ngt_upgrade_v2.py\", line 47, in invoke_module\n    runpy.run
_module(mod_name='ansible_collections.nutanix.ncp.plugins.modules.ntnx_vms_ngt_upgrade_v2', init_globals=dict(_module_fqn='ansible_collections.nutanix.ncp.plugins.modules.ntnx_vms_ngt_upgrade_v2', _modlib_path=modlib_path),
\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_nutanix.ncp.ntnx_vms_ngt_upgrade_v2_payl
oad_sloy1clf/ansible_nutanix.ncp.ntnx_vms_ngt_upgrade_v2_payload.zip/ansible_collections/nutanix/ncp/plugins/modules/ntnx_vms_ngt_upgrade_v2.py\", line 232, in <module>\n  File \"/tmp/ansible_nutanix.ncp.ntnx_vms_ngt_upgrad
e_v2_payload_sloy1clf/ansible_nutanix.ncp.ntnx_vms_ngt_upgrade_v2_payload.zip/ansible_collections/nutanix/ncp/plugins/modules/ntnx_vms_ngt_upgrade_v2.py\", line 228, in main\n  File \"/tmp/ansible_nutanix.ncp.ntnx_vms_ngt_u
pgrade_v2_payload_sloy1clf/ansible_nutanix.ncp.ntnx_vms_ngt_upgrade_v2_payload.zip/ansible_collections/nutanix/ncp/plugins/modules/ntnx_vms_ngt_upgrade_v2.py\", line 223, in run_module\n  File \"/tmp/ansible_nutanix.ncp.ntn
x_vms_ngt_upgrade_v2_payload_sloy1clf/ansible_nutanix.ncp.ntnx_vms_ngt_upgrade_v2_payload.zip/ansible_collections/nutanix/ncp/plugins/modules/ntnx_vms_ngt_upgrade_v2.py\", line 200, in upgrade_ngt\n  File \"/tmp/ansible_nut
anix.ncp.ntnx_vms_ngt_upgrade_v2_payload_sloy1clf/ansible_nutanix.ncp.ntnx_vms_ngt_upgrade_v2_payload.zip/ansible_collections/nutanix/ncp/plugins/module_utils/v4/prism/tasks.py\", line 47, in wait_for_completion\n  File \"/
tmp/ansible_nutanix.ncp.ntnx_vms_ngt_upgrade_v2_payload_sloy1clf/ansible_nutanix.ncp.ntnx_vms_ngt_upgrade_v2_payload.zip/ansible_collections/nutanix/ncp/plugins/module_utils/v4/prism/pc_api_client.py\", line 26, in get_pc_api_client\nTypeError: AnsibleModule.fail_json() takes 2 positional arguments but 3 were given\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP ********************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
**Expected behavior**
NGT upgraded to the latest version after the execution of this playbook.

**Additional context**

I also attach the output of the API response which I have done from browser:

https://<nutanix_host>:9440/api/vmm/v4.0/ahv/config/vms/<nutanix_vm_uuid>/guest-tools

```
{
  "data": {
    "version": "4.0",
    "isInstalled": true,
    "isIsoInserted": true,
    "availableVersion": "4.2",
    "guestOsVersion": "linux:64:Ubuntu-20.04.6",
    "isReachable": false,
    "$reserved": {
      "$fv": "v4.r0"
    },
    "$objectType": "vmm.v4.ahv.config.GuestTools",
    "isEnabled": true
  },
  "$reserved": {
    "$fv": "v4.r0"
  },
  "$objectType": "vmm.v4.ahv.config.GetGuestToolsApiResponse",
  "metadata": {
    "flags": [
      {
        "$reserved": {
          "$fv": "v1.r0"
        },
        "$objectType": "common.v1.config.Flag",
        "name": "hasError",
        "value": false
      },
      {
        "$reserved": {
          "$fv": "v1.r0"
        },
        "$objectType": "common.v1.config.Flag",
        "name": "isPaginated",
        "value": false
      },
      {
        "$reserved": {
          "$fv": "v1.r0"
        },
        "$objectType": "common.v1.config.Flag",
        "name": "isTruncated",
        "value": false
      }
    ],
    "$reserved": {
      "$fv": "v1.r0"
    },
    "$objectType": "common.v1.response.ApiResponseMetadata",
    "links": [
      {
        "$reserved": {
          "$fv": "v1.r0"
        },
        "$objectType": "common.v1.response.ApiLink",
        "href": "https://<nutanix_pc>:9440/api/vmm/v4.0/ahv/config/vms/<nutanix_vm_uuid>/guest-tools",
        "rel": "self"
      },
      {
        "href": "https://<nutanix_pc>:9440/api/vmm/v4.0/ahv/config/vms/<nutanix_vm_uuid>",
        "rel": "via"
      }
    ]
  }
}
```

**Comment by bhati-pradeep** [comment]
Hi @khismatullinmax  seems there are missing requirements in your environment. Usually when you download from ansible galaxy portal you get them by default.
Please pip install this requirements : https://github.com/nutanix/nutanix.ansible/blob/main/requirements.txt

**Comment by khismatullinmax** [comment]
Hi @bhati-pradeep, 

Ansible-galaxy doesn't install any pip requirements from the collection, I added to my playbook this task which installs all required python packages like from nutanix.ncp requirements.txt file (except `pip` and `ansible-core` because I have the ansible-core 2.18.3 now and your [requirements ](https://github.com/nutanix/nutanix.ansible/blob/main/requirements.txt) contains strong value of the ansible-core version - ansible-core==2.15.0): 

``` 
 - name: Install required Python packages
    pip:
      name:
        - ipaddress~=1.0.23
        - setuptools~=44.1.1
        - requests~=2.26.0
        - black==22.8.0
        - flake8==4.0.1
        - isort==5.9.3
        - coverage==6.5.0
        - shyaml==0.6.2
        - ntnx-clustermgmt-py-client==4.0.1
        - ntnx-iam-py-client==4.0.1
        - ntnx-microseg-py-client==4.0.1
        - ntnx-networking-py-client==4.0.1
        - ntnx-prism-py-client==4.0.1
        - ntnx-vmm-py-client==4.0.1
        - ntnx-volumes-py-client==4.0.1
        - ntnx-dataprotection-py-client==4.0.1
      state: present
```

Now it works.
