### ISSUE TITLE
[Imprv] change ntnx_templates_v2 initial versionName and versionDescription behaviour

### ISSUE THREAD

**Issue by karlatec** [nutanix/nutanix.ansible#620]
**Describe the request**

I would like to suggest a change to `ntnx_templates_v2` behavior. When creating first version of the template it would be great to have a possibility of setting custom values for `versionName` and `versionDescription`.
Currently these are set to `Initial version` and `Created from VM: [...]`.

Current behavior forces user to use additional steps/tasks in the playbook - registering `ntnx_templates_v2` response, extracting template's `ext_id`, then finally updating it's name and description. It could be set in one go, similarly to (for example) Ansible Docker module - where built Docker image tag (which I think kind of resembles "versionName") can be set in one task, not forcing user to do it separately. 

**Current behaviour**

Running Ansible task:
```
    - name: Create VM template
      nutanix.ncp.ntnx_templates_v2:
        nutanix_host: "{{ pc_ip }}"
        wait: true
        state: present
        validate_certs: false
        template_name: "{{ vm_template_name }}"
        template_description: "{{ vm_template_desc}}"
        template_version_spec:
          version_source:
            template_vm_reference:
              ext_id: "{{ vm_info.response[0].ext_id }}"
```
results in VM template created with `versionName` and `versionDescription` set to `Initial version` and `Created from VM: [...]`.

**Expected behaviour**
`versionName` and `versionDescription` set to user-provided values even for v1 of created template.
