### ISSUE TITLE
[Imprv] add functionality to remove cloud-init disk to module ntnx_vms_cd_rom_iso_v2

### ISSUE THREAD

**Issue by cptBlackBeer** [nutanix/nutanix.ansible#621]
**Describe the request**
Make it possible to remove cloud-init disk reference from cd rom.
Generally it would be nice to have a simpler task to simply empty the CD ROM no matter what is mounted.

**Current behaviour**
When creating a VM with cloud-init script the cloud-init script is mounted in CD-ROM which is perfectly fine. But with the module ntnx_vms_cd_rom_iso_v2 only image or disk references can be removed. 
The cloud-init script is neither as shown in this output.
```
"response": [
            {
                "backing_info": {
                    "data_source": null,
                    "disk_ext_id": "2228dada-9076-4fb8-a345-cadfae4b9298",
                    "disk_size_bytes": 382976,
                    "is_migration_in_progress": false,
                    "storage_config": null,
                    "storage_container": {
                        "ext_id": "26a06f58-4b50-4f3a-add6-64964cb04077"
                    }
                },
                "disk_address": {
                    "bus_type": "IDE",
                    "index": 0
                },
                "ext_id": "2228dada-9076-4fb8-a345-cadfae4b9298",
                "iso_type": "GUEST_CUSTOMIZATION",
                "links": null,
                "tenant_id": null
            }
        ],
```

**Expected behaviour**
Having a simple task to empty the cd rom no matter what is mounted.
```yml
- name: empty cd rom
  nutanix.ncp.ntnx_vms_cd_rom_iso_v2:
    vm_ext_id: "vm_ext_id"
    ext_id: "ext_id"
    empty: true
```

or add the possibility to remove disk_ext_id
```yml
- name: Remove cloud-init from CD ROM
  nutanix.ncp.ntnx_vms_cd_rom_iso_v2:
    vm_ext_id: "vm_ext_id"
    ext_id: "ext_id"
    backing_info:
      disk_ext_id: "ext_id"
    state: absent
```

**Comment by george-ghawali** [comment]
Hi @cptBlackBeer @EdwinKM 
It works fine for me in Ansible with the same scenario, Can you please try using these playbooks?

- Create VM with cloud init
```
- name: Create VM
  ntnx_vms_v2:
    state: present
    name: "vm_name"
    cluster:
      ext_id: "cluster_ext_id"
    guest_customization:
      config:
        cloudinit:
          datasource_type: CONFIG_DRIVE_V2
          cloud_init_script:
            user_data:
              value: I2Nsb3VkLWNvbmZpZwpkaXNhYmxlX3Jvb3Q6IGZhbHNlCnNzaF9wd2F1dGg6ICAgdHJ1ZQ==
  register: result
  ignore_errors: true
```

- Fetch VM info

```
- name: Fetch VM info
  ntnx_vms_info_v2:
    ext_id: "{{ vm_uuid }}"
  register: result
```
- Sample response from fetching VM

```
"cd_roms": [
                {
                    "backing_info": {
                        "data_source": null,
                        "disk_ext_id": "598ca0c6-49da-4da6-b7de-f6b310e0bd8c",
                        "disk_size_bytes": 382976,
                        "is_migration_in_progress": false,
                        "storage_config": null,
                        "storage_container": {
                            "ext_id": "46dc02ed-4a76-442a-b0da-53aa73df2d5c"
                        }
                    },
                    "disk_address": {
                        "bus_type": "IDE",
                        "index": 0
                    },
                    "ext_id": "598ca0c6-49da-4da6-b7de-f6b310e0bd8c",
                    "iso_type": "GUEST_CUSTOMIZATION",
                    "links": null,
                    "tenant_id": null
                }
            ],
```

- Eject CD ROM using ntnx_vms_cd_rom_iso_v2 by setting state as absent

```
- name: Eject ISO from CD ROM of a VM
  ntnx_vms_cd_rom_iso_v2:
    state: absent
    vm_ext_id: "{{ vm_uuid }}"
    ext_id: "{{ cd_rom_ext_id }}"
  register: result
  ignore_errors: true
```

- Fetch VM info

```
- name: Fetch VM info
  ntnx_vms_info_v2:
    ext_id: "{{ vm_uuid }}"
  register: result
```

- Sample response from fetching VM

```
"cd_roms": [
                {
                    "backing_info": null,
                    "disk_address": {
                        "bus_type": "IDE",
                        "index": 0
                    },
                    "ext_id": "598ca0c6-49da-4da6-b7de-f6b310e0bd8c",
                    "iso_type": "OTHER",
                    "links": null,
                    "tenant_id": null
                }
            ],
```

We are closing this ticket as the issue has been addressed.
If you encounter any further problems while following the steps above, feel free to reopen the issue or create a new one.
Thank you for your contribution!
