### ISSUE TITLE
[Imprv] add functionality witness_configuration_list to module ntnx_recovery_plans

### ISSUE THREAD

**Issue by viviengarot** [nutanix/nutanix.ansible#623]
**Describe the request**

Make it possible to declare a witness UUID and its failover timeout during protection plan creation.
This functionality is already available in the Prism v3 API, recovery_plans endpoint, under ressources > parameters > witness_configuration_list

**Current behaviour**

With no support for witness in this module we are not allowing users to configure Failure Execution Mode to automatic during Recovery Plan creation.

**Expected behaviour**

Add an optional witness parameter to ntnx_recovery_plans module

```
- name: Create recovery plan
  ntnx_recovery_plans:
    nutanix_host: "{{ ip }}"
    nutanix_username: "{{ username }}"
    nutanix_password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    state: "present"
    name: test-integration-rp-updated
    desc: test-integration-rp-desc-updated
    stages:
        categories:
          - key: Environment
            value: Production
            enable_script_exec: true
      url: "{{primary_az_url}}"
    recovery_location:
      url: "{{recovery_az_url}}"
    network_type: STRETCH
    network_mappings:
      - primary:
          test:
            name: "{{static.name}}"
            gateway_ip: "{{static.gateway_ip}}"
            prefix: "{{static.network_prefix}}"
          prod:
            name: "{{static.name}}"
            gateway_ip: "{{static.gateway_ip}}"
            prefix: "{{static.network_prefix}}"
        recovery:
          test:
            name: "{{dr.recovery_site_network}}"
          prod:
            name: "{{dr.recovery_site_network}}"
    witness:
      url: "{{witness_url}}"
      failover_delay: 10
```
