### ISSUE TITLE
[Bug] Sysprep option lead to stuck tasks in module nutanix.ncp.ntnx_vms_v2

### ISSUE THREAD

**Issue by motorbass0** [nutanix/nutanix.ansible#654]
**Describe the bug**
When configuring sysprep option , it creates Prism Central tasks that are stuck forever. I test it in 2 differents ways : 
1) At VM creation using module nutanix.ncp.ntnx_vms_v2
2) OR post VM creation with module nutanix.ncp.ntnx_vms_stage_guest_customization_v2 

**To Reproduce**
Using nutanix.ncp.ntnx_vms_v2 : 

```
  - name: Deploy Windows Server 2025 VM
    nutanix.ncp.ntnx_vms_v2:
      nutanix_host: "{{ nutanix_host }}"
      nutanix_username: "{{ nutanix_username }}"
      nutanix_password: "{{ nutanix_password }}"
      validate_certs: False

      name: "{{ nom_vm }}"
      description: "{{ description_vm }}"
      hardware_clock_timezone: "UTC"

      cluster:
        ext_id: "{{ cluster_uuid }}"

      boot_config:
        uefi_boot:
          is_secure_boot_enabled: false

      categories:
        - ext_id: "{{ categorie_uuid }}"

### CPU/Memory ###
      num_sockets: "{{ nb_vcpu }}"
      num_cores_per_socket: "{{ nb_core }}"
      memory_size_bytes: '{{  gb_ram  | human_to_bytes(default_unit="G") }}'

### Storage ###
      disks:
        - backing_info:
            vm_disk:
              disk_size_bytes: '{{ 100 | human_to_bytes(default_unit="G") }}'
              data_source:
                reference:
                  image_reference:
                    image_ext_id: "{{ image_uuid }}"

### Network ###
      nics:
        - network_info:
            subnet:
              ext_id: "{{ subnet_uuid }}"

      guest_customization:
        config:
          sysprep:
            install_type: PREPARED
            sysprep_script:
              unattendxml:
               value: "{{ lookup('file', './scripts/unattend.xml') | b64encode }}"
```
Note : Even if I replace value content by already b64encode content, result is the same.

In my second try below, I removed ```guest_customization``` statement when VM is created, then create the following task after vm creation :

```
  - name: guest custom
    nutanix.ncp.ntnx_vms_stage_guest_customization_v2:
      ext_id: "5a397716-f820-49b4-66da-c862de43a193"
      config:
        sysprep:
          install_type: PREPARED
          sysprep_script:
            unattendxml:
             value: "{{ lookup('file', './scripts/unattend.xml') | b64encode }}"
```

**Stack trace**
Ansible task is running without error, it creates tasks on Prism Central which is stuck forever (and so ansible task too).

**Expected behavior**
unattend.xml script should be mounted to the VM, however task is running forever and don't have any more input from Prism Central perspective.
I have to manually kill tasks using ecli/ergon CLI on Prism Element CLI.

**Additional context**
I used to make this configuration using v3 API and v1 ansible module without any issue with the same content file.
